POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Jão",
    "email": "jao@jao.com",
    "password": "12345678"
}

###
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "Mar",
    "description": "Azul e calmo",
    "type": "normal",
    "authorId": "246810",
}
###
POST http://localhost:3003/friend/add
Content-Type: application/json

{
    "user1_id": "0c503f5e-1213-45aa-8d76-a02b97c67c6c",
    "user2_id": "0c7f41f0-dd7d-4b50-9dba-f3935334da85",
}
###
GET http://localhost:3003/post/all
Content-Type: application/json