POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Jão",
    "email": "jao@jao.com",
    "password": "12345678"
}

###
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "Mar",
    "description": "Azul e calmo",
    "type": "normal",
    "authorId": "246810",
}
###
POST http://localhost:3003/friendship/create
Content-Type: application/json

{
    "user": "95c61a87-c100-4927-9f66-a5d9d2263de7",
    "friendship": "0c7f41f0-dd7d-4b50-9dba-f3935334da85"
}
###
GET http://localhost:3003/post/getbyid/2cb6aad8-8d03-4ffd-b9fa-84165abdd6e0
Content-Type: application/json

###
GET http://localhost:3003/post/all
Content-Type: application/json

###
DELETE http://localhost:3003/friendship/delete/b0d3c373-e7b9-45ab-acb8-52452fbca833
Content-Type: application/json
